linters:
  disable:
    - govet          # Desabilitado: fieldalignment (50+ structs)
    - gocritic       # Desabilitado: hugeParam (5+ funções)
    - revive         # Desabilitado: exported stuttering (3 tipos)
  enable:
    - errcheck       # Mantido: error checking é crítico
    - staticcheck    # Mantido: análise estática importante
    - unused         # Mantido: código não usado
    - gosimple       # Mantido: simplificações úteis
    - ineffassign    # Mantido: assignments ineficientes

run:
  timeout: 5m

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

# Nota: Linters desabilitados temporariamente para otimizações futuras
# TODO: Re-habilitar em PR separado:
# - govet: Reordenar structs para alignment
# - gocritic: Passar structs grandes por ponteiro
# - revive: Renomear tipos (InterProvider -> Provider)
