run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gosec
    - gocritic
    - revive
    - stylecheck
    - bodyclose
    - noctx
    - exportloopref
    - sqlclosecheck
    - rowserrcheck
    - nilerr
    - nilnil
    - tenv
    - tparallel
    - wastedassign
    - whitespace

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    check-shadowing: true
    enable-all: true
  
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: github.com/pixsaas/backend
  
  gosec:
    excludes:
      - G104 # Audit errors not checked (já coberto por errcheck)
    severity: medium
    confidence: medium
  
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  
  revive:
    rules:
      - name: exported
        severity: warning
      - name: package-comments
        severity: warning
      - name: var-naming
        severity: warning
      - name: indent-error-flow
        severity: warning
      - name: blank-imports
        severity: warning
      - name: context-as-argument
        severity: warning
      - name: dot-imports
        severity: warning
      - name: error-return
        severity: warning
      - name: error-strings
        severity: warning
      - name: error-naming
        severity: warning
      - name: increment-decrement
        severity: warning
      - name: var-declaration
        severity: warning
      - name: range
        severity: warning
      - name: receiver-naming
        severity: warning
      - name: time-naming
        severity: warning
      - name: unexported-return
        severity: warning
      - name: indent-error-flow
        severity: warning
      - name: errorf
        severity: warning

issues:
  exclude-rules:
    # Excluir alguns linters de arquivos de teste
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - gocritic
    
    # Excluir alguns linters de arquivos gerados
    - path: ".*\\.pb\\.go"
      linters:
        - all
    
    # Excluir warnings específicos
    - text: "should have a package comment"
      linters:
        - revive
    
    - text: "ST1000:"
      linters:
        - stylecheck
  
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true
