name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    
    - name: Run tests
      working-directory: ./backend
      run: go test -v ./...
    
    - name: Build binaries
      working-directory: ./backend
      run: |
        # Linux AMD64
        GOOS=linux GOARCH=amd64 go build -o bin/pix-saas-api-linux-amd64 ./cmd/api
        GOOS=linux GOARCH=amd64 go build -o bin/pix-saas-cli-linux-amd64 ./cmd/cli
        
        # Linux ARM64
        GOOS=linux GOARCH=arm64 go build -o bin/pix-saas-api-linux-arm64 ./cmd/api
        GOOS=linux GOARCH=arm64 go build -o bin/pix-saas-cli-linux-arm64 ./cmd/cli
        
        # macOS AMD64
        GOOS=darwin GOARCH=amd64 go build -o bin/pix-saas-api-darwin-amd64 ./cmd/api
        GOOS=darwin GOARCH=amd64 go build -o bin/pix-saas-cli-darwin-amd64 ./cmd/cli
        
        # macOS ARM64 (Apple Silicon)
        GOOS=darwin GOARCH=arm64 go build -o bin/pix-saas-api-darwin-arm64 ./cmd/api
        GOOS=darwin GOARCH=arm64 go build -o bin/pix-saas-cli-darwin-arm64 ./cmd/cli
        
        # Windows AMD64
        GOOS=windows GOARCH=amd64 go build -o bin/pix-saas-api-windows-amd64.exe ./cmd/api
        GOOS=windows GOARCH=amd64 go build -o bin/pix-saas-cli-windows-amd64.exe ./cmd/cli
    
    - name: Generate checksums
      working-directory: ./backend/bin
      run: |
        sha256sum * > checksums.txt
    
    - name: Create Release Notes
      id: release-notes
      run: |
        echo "## What's Changed" > release-notes.md
        git log $(git describe --tags --abbrev=0 HEAD^)..HEAD --pretty=format:"- %s (%h)" >> release-notes.md
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          backend/bin/pix-saas-api-*
          backend/bin/pix-saas-cli-*
          backend/bin/checksums.txt
        body_path: release-notes.md
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
